In [1]:
x = 3.5

3.5

In [2]:
typeof(x)

Float64

In [4]:
s = bits(x)   # en 0.7: bitstring

"0100000000001100000000000000000000000000000000000000000000000000"

In [6]:
typeof(s)

String

In [7]:
length(s)

64

Ver los bits de otra forma:

In [9]:
y = parse(Int, s, 2)

4615063718147915776

In [10]:
typeof(y)

Int64

In [11]:
bits(y)

"0100000000001100000000000000000000000000000000000000000000000000"

In [12]:
bits(x)

"0100000000001100000000000000000000000000000000000000000000000000"

In [13]:
y

4615063718147915776

In [14]:
x

3.5

In [15]:
reinterpret(Int64, x)

4615063718147915776

In [20]:
reinterpret(Int32, [x])

2-element Array{Int32,1}:
          0
 1074528256

In [24]:
reinterpret(Float32, [x])

2-element Array{Float32,1}:
 0.0   
 2.1875

In [25]:
reinterpret(Float32, [9])

2-element Array{Float32,1}:
 1.26117f-44
 0.0        

In [28]:
reinterpret(Int32, [9])

2-element Array{Int32,1}:
 9
 0

In [27]:
bits(9)

"0000000000000000000000000000000000000000000000000000000000001001"

In [21]:
bits(x)

"0100000000001100000000000000000000000000000000000000000000000000"

In [23]:
parse(Int, bits(x)[1:32], 2)

1074528256

In [19]:
?reinterpret

search: reinterpret



```
reinterpret(type, A)
```

Change the type-interpretation of a block of memory. For arrays, this constructs an array with the same binary data as the given array, but with the specified element type. For example, `reinterpret(Float32, UInt32(7))` interprets the 4 bytes corresponding to `UInt32(7)` as a [`Float32`](@ref).

!!! warning
    It is not allowed to `reinterpret` an array to an element type with a larger alignment then the alignment of the array. For a normal `Array`, this is the alignment of its element type. For a reinterpreted array, this is the alignment of the `Array` it was reinterpreted from. For example, `reinterpret(UInt32, UInt8[0, 0, 0, 0])` is not allowed but `reinterpret(UInt32, reinterpret(UInt8, Float32[1.0]))` is allowed.


# Examples

```jldoctest
julia> reinterpret(Float32, UInt32(7))
1.0f-44

julia> reinterpret(Float32, UInt32[1 2 3 4 5])
1×5 Array{Float32,2}:
 1.4013f-45  2.8026f-45  4.2039f-45  5.60519f-45  7.00649f-45
```


In [29]:
Intervalo

LoadError: UndefVarError: Intervalo not defined

## Desestructuración de tuplas

In [30]:
x = (3, 4)

(3, 4)

In [31]:
a = x[1]
b = x[2]

4

In [33]:
(a, b) = x

(3, 4)

In [34]:
f(x::Tuple) = ( (a, b) = x; (2a, 2b) )

f (generic function with 1 method)

In [35]:
function f(x::Tuple)
    a, b = x
    return (2a, 2b)
end

f (generic function with 1 method)

In [36]:
function f2(x::Tuple)
    return (2x[1] - x[1]^2 + 2x[2], x[2] - x[1])
end

f2 (generic function with 1 method)

In [37]:
function f2(x::Tuple)
    a, b = x
    return (2a - a^2 + 2a, a - b)
end

f2 (generic function with 1 method)

In [38]:

x = (1, 2, 3)

(1, 2, 3)

In [39]:
a, b = x

(1, 2, 3)

In [40]:
a

1

In [41]:
b

2